#
# 服务器配置
#
server:
  port: ${SERVER_PORT:8080}


spring:
  servlet:
    async-supported: true # 确保异步支持已开启
  jmx:
    enabled: true
  application:
    name: mrcms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false # 禁止将日期序列化为时间戳
  mvc:
    converters:
      preferred-json-mapper: jackson

    contentnegotiation:
      favor-path-extension: true
      default-content-types: application/json
    pathmatch:
      use-suffix-pattern: true
      use-registered-suffix-pattern: true
    servlet:
      load-on-startup: 2
      async-supported: true
  main:
    allow-bean-definition-overriding: true
  freemarker:
    suffix: .html
    charset: UTF-8
    check-template-location: true
    template-loader-path: classpath:/templates/content/
    settings:
      classic_compatible=true:  # 数据库配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mushroom.db.host}:${mushroom.db.port}/${mushroom.db.demo}?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${mushroom.db.user}
    password: ${mushroom.db.pass}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 200
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      pool-name: MrcmsPool
logging:
  level:
    root: info

# 验证码
kaptcha:
  height: 50
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 40
  background-color:
    from: lightGray
    to: white
  border:
    enabled: true
    color: black
    thickness: 1